import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { lessons, questions } from "./schema";
import * as dotenv from "dotenv";
dotenv.config();

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

async function seed() {
  console.log("Seeding 25 lessons...");

  const insertedLessons = await db
    .insert(lessons)
    .values([
      {
        title: "Colors",
        description:
          "Learn to describe colors and talk about what you see around you.",
        category: "Daily Life",
        order: 4,
      },
      {
        title: "Family",
        description: "Talk about your family members and relationships.",
        category: "Daily Life",
        order: 5,
      },
      {
        title: "Travel",
        description:
          "Navigate airports, hotels, and get around in a Spanish-speaking country.",
        category: "Travel",
        order: 6,
      },
      {
        title: "Weather",
        description: "Talk about the weather and seasons in Spanish.",
        category: "Daily Life",
        order: 7,
      },
      {
        title: "Days & Months",
        description: "Learn the days of the week and months of the year.",
        category: "Basics",
        order: 8,
      },
      {
        title: "Time",
        description: "Tell the time and talk about daily schedules.",
        category: "Basics",
        order: 9,
      },
      {
        title: "Shopping",
        description: "Buy things, ask for prices, and navigate markets.",
        category: "Travel",
        order: 10,
      },
      {
        title: "Body Parts",
        description: "Name parts of the body and describe how you feel.",
        category: "Health",
        order: 11,
      },
      {
        title: "At the Doctor",
        description: "Describe symptoms and understand medical advice.",
        category: "Health",
        order: 12,
      },
      {
        title: "Emotions",
        description: "Express how you feel and understand others emotions.",
        category: "Daily Life",
        order: 13,
      },
      {
        title: "Animals",
        description: "Name common animals and describe them.",
        category: "Nature",
        order: 14,
      },
      {
        title: "Nature",
        description: "Talk about the outdoors, landscapes, and environment.",
        category: "Nature",
        order: 15,
      },
      {
        title: "Sports",
        description: "Talk about sports, exercise, and staying active.",
        category: "Lifestyle",
        order: 16,
      },
      {
        title: "Hobbies",
        description: "Describe what you enjoy doing in your free time.",
        category: "Lifestyle",
        order: 17,
      },
      {
        title: "Work",
        description: "Talk about jobs, workplaces, and professional life.",
        category: "Lifestyle",
        order: 18,
      },
      {
        title: "School",
        description: "Navigate school vocabulary and academic subjects.",
        category: "Basics",
        order: 19,
      },
      {
        title: "Technology",
        description: "Talk about phones, computers, and the internet.",
        category: "Lifestyle",
        order: 20,
      },
      {
        title: "Directions",
        description: "Ask for and give directions to get around a city.",
        category: "Travel",
        order: 21,
      },
      {
        title: "Transport",
        description: "Use buses, trains, taxis, and other transport.",
        category: "Travel",
        order: 22,
      },
      {
        title: "Clothes",
        description: "Describe what you are wearing and go clothes shopping.",
        category: "Daily Life",
        order: 23,
      },
      {
        title: "House & Home",
        description: "Describe your home and talk about household tasks.",
        category: "Daily Life",
        order: 24,
      },
      {
        title: "Celebrations",
        description: "Talk about holidays, birthdays, and special occasions.",
        category: "Culture",
        order: 25,
      },
      {
        title: "Music",
        description: "Talk about music, instruments, and your taste in songs.",
        category: "Culture",
        order: 26,
      },
      {
        title: "Movies & TV",
        description: "Discuss films, shows, and entertainment.",
        category: "Culture",
        order: 27,
      },
      {
        title: "Advanced Phrases",
        description: "Master complex expressions and nuanced conversation.",
        category: "Advanced",
        order: 28,
      },
    ])
    .returning();

  const [
    colors,
    family,
    travel,
    weather,
    daymonth,
    time,
    shopping,
    body,
    doctor,
    emotions,
    animals,
    nature,
    sports,
    hobbies,
    work,
    school,
    tech,
    directions,
    transport,
    clothes,
    house,
    celebrations,
    music,
    movies,
    advanced,
  ] = insertedLessons;

  await db.insert(questions).values([
    // Colors
    {
      lessonId: colors.id,
      prompt: "Translate: rojo",
      options: ["Blue", "Green", "Red", "Yellow"],
      correctIndex: 2,
      hint: "Rojo = red",
    },
    {
      lessonId: colors.id,
      prompt: "Translate: azul",
      options: ["Blue", "Purple", "Black", "Grey"],
      correctIndex: 0,
      hint: "Azul = blue",
    },
    {
      lessonId: colors.id,
      prompt: 'How do you say "green" in Spanish?',
      options: ["Amarillo", "Naranja", "Verde", "Blanco"],
      correctIndex: 2,
      hint: "Think of verde as verdant",
    },
    {
      lessonId: colors.id,
      prompt: "Translate: negro",
      options: ["White", "Brown", "Grey", "Black"],
      correctIndex: 3,
      hint: "Negro = black",
    },
    {
      lessonId: colors.id,
      prompt: "Translate: blanco",
      options: ["White", "Beige", "Cream", "Silver"],
      correctIndex: 0,
      hint: "Blanco = white",
    },
    {
      lessonId: colors.id,
      prompt: 'How do you say "yellow" in Spanish?',
      options: ["Morado", "Amarillo", "Rosado", "Gris"],
      correctIndex: 1,
      hint: "Amarillo = yellow",
    },
    {
      lessonId: colors.id,
      prompt: "Translate: morado",
      options: ["Orange", "Pink", "Purple", "Brown"],
      correctIndex: 2,
      hint: "Morado = purple",
    },
    {
      lessonId: colors.id,
      prompt: "¿De qué color es el cielo?",
      options: ["It is green", "It is red", "It is blue", "It is white"],
      correctIndex: 2,
      hint: "Cielo = sky",
    },

    // Family
    {
      lessonId: family.id,
      prompt: "Translate: la madre",
      options: ["Sister", "Grandmother", "Mother", "Aunt"],
      correctIndex: 2,
      hint: "Madre sounds like mother",
    },
    {
      lessonId: family.id,
      prompt: "Translate: el padre",
      options: ["Brother", "Father", "Uncle", "Grandfather"],
      correctIndex: 1,
      hint: "Padre = father",
    },
    {
      lessonId: family.id,
      prompt: 'How do you say "brother" in Spanish?',
      options: ["Hermana", "Primo", "Hermano", "Tío"],
      correctIndex: 2,
      hint: "Hermano/Hermana = brother/sister",
    },
    {
      lessonId: family.id,
      prompt: "Translate: la abuela",
      options: ["Mother", "Aunt", "Cousin", "Grandmother"],
      correctIndex: 3,
      hint: "Abuela = grandmother",
    },
    {
      lessonId: family.id,
      prompt: "Translate: el hijo",
      options: ["Father", "Brother", "Son", "Uncle"],
      correctIndex: 2,
      hint: "Hijo = son",
    },
    {
      lessonId: family.id,
      prompt: 'How do you say "wife" in Spanish?',
      options: ["Novia", "Hermana", "Esposa", "Prima"],
      correctIndex: 2,
      hint: "Esposa = wife",
    },
    {
      lessonId: family.id,
      prompt: "Translate: los tíos",
      options: [
        "The cousins",
        "The grandparents",
        "The siblings",
        "The aunts and uncles",
      ],
      correctIndex: 3,
      hint: "Tío = uncle, tía = aunt",
    },
    {
      lessonId: family.id,
      prompt: "¿Cuántos hermanos tienes?",
      options: [
        "How old are you?",
        "Where do you live?",
        "How many siblings do you have?",
        "What is your name?",
      ],
      correctIndex: 2,
      hint: "Cuántos = how many",
    },

    // Travel
    {
      lessonId: travel.id,
      prompt: "¿Dónde está el aeropuerto?",
      options: [
        "Where is the hotel?",
        "Where is the airport?",
        "Where is the train station?",
        "Where is the bus stop?",
      ],
      correctIndex: 1,
      hint: "Aeropuerto = airport",
    },
    {
      lessonId: travel.id,
      prompt: "Translate: el pasaporte",
      options: ["The ticket", "The suitcase", "The passport", "The visa"],
      correctIndex: 2,
      hint: "Pasaporte = passport",
    },
    {
      lessonId: travel.id,
      prompt: "Translate: el boleto",
      options: ["The luggage", "The passport", "The map", "The ticket"],
      correctIndex: 3,
      hint: "Boleto = ticket",
    },
    {
      lessonId: travel.id,
      prompt: "¿A qué hora sale el tren?",
      options: [
        "Where does the train go?",
        "How much is the train?",
        "What time does the train leave?",
        "How long is the train ride?",
      ],
      correctIndex: 2,
      hint: "Sale = leaves",
    },
    {
      lessonId: travel.id,
      prompt: "Translate: la maleta",
      options: ["The map", "The suitcase", "The ticket", "The passport"],
      correctIndex: 1,
      hint: "Maleta = suitcase",
    },
    {
      lessonId: travel.id,
      prompt: 'How do you say "I am lost" in Spanish?',
      options: [
        "Estoy cansado",
        "Estoy perdido",
        "Estoy enfermo",
        "Estoy ocupado",
      ],
      correctIndex: 1,
      hint: "Perdido = lost",
    },
    {
      lessonId: travel.id,
      prompt: "¿Puede llamar un taxi?",
      options: [
        "Can you call a doctor?",
        "Can you call a taxi?",
        "Can you call the police?",
        "Can you call my hotel?",
      ],
      correctIndex: 1,
      hint: "Taxi is the same word!",
    },
    {
      lessonId: travel.id,
      prompt: "Translate: la reservación",
      options: [
        "The reservation",
        "The destination",
        "The departure",
        "The arrival",
      ],
      correctIndex: 0,
      hint: "Similar to the English word",
    },

    // Weather
    {
      lessonId: weather.id,
      prompt: "¿Qué tiempo hace hoy?",
      options: [
        "What time is it?",
        "What is the weather like today?",
        "What day is it today?",
        "What season is it?",
      ],
      correctIndex: 1,
      hint: "Tiempo = weather or time",
    },
    {
      lessonId: weather.id,
      prompt: "Translate: hace frío",
      options: ["It is hot", "It is windy", "It is cold", "It is raining"],
      correctIndex: 2,
      hint: "Frío = cold",
    },
    {
      lessonId: weather.id,
      prompt: "Translate: está lloviendo",
      options: [
        "It is snowing",
        "It is sunny",
        "It is cloudy",
        "It is raining",
      ],
      correctIndex: 3,
      hint: "Lluvia = rain",
    },
    {
      lessonId: weather.id,
      prompt: 'How do you say "sunny" in Spanish?',
      options: ["Nublado", "Soleado", "Ventoso", "Nevado"],
      correctIndex: 1,
      hint: "Sol = sun",
    },
    {
      lessonId: weather.id,
      prompt: "Translate: la nieve",
      options: ["The rain", "The wind", "The snow", "The storm"],
      correctIndex: 2,
      hint: "Nieve = snow",
    },
    {
      lessonId: weather.id,
      prompt: "Translate: hace calor",
      options: ["It is cold", "It is hot", "It is windy", "It is humid"],
      correctIndex: 1,
      hint: "Calor = heat",
    },
    {
      lessonId: weather.id,
      prompt: 'How do you say "umbrella" in Spanish?',
      options: ["Impermeable", "Paraguas", "Abrigo", "Bufanda"],
      correctIndex: 1,
      hint: "Para = stop, aguas = waters",
    },
    {
      lessonId: weather.id,
      prompt: "Translate: la tormenta",
      options: ["The breeze", "The fog", "The thunder", "The storm"],
      correctIndex: 3,
      hint: "Tormenta = storm",
    },

    // Days & Months
    {
      lessonId: daymonth.id,
      prompt: "Translate: lunes",
      options: ["Tuesday", "Sunday", "Monday", "Wednesday"],
      correctIndex: 2,
      hint: "Luna = moon, Monday = moon day",
    },
    {
      lessonId: daymonth.id,
      prompt: "Translate: viernes",
      options: ["Thursday", "Friday", "Saturday", "Wednesday"],
      correctIndex: 1,
      hint: "TGIF — viernes = Friday",
    },
    {
      lessonId: daymonth.id,
      prompt: 'How do you say "January" in Spanish?',
      options: ["Junio", "Julio", "Enero", "Junio"],
      correctIndex: 2,
      hint: "Enero = January",
    },
    {
      lessonId: daymonth.id,
      prompt: "Translate: agosto",
      options: ["April", "June", "October", "August"],
      correctIndex: 3,
      hint: "Agosto sounds like August",
    },
    {
      lessonId: daymonth.id,
      prompt: "Translate: el fin de semana",
      options: ["The holiday", "The weekday", "The weekend", "The vacation"],
      correctIndex: 2,
      hint: "Fin = end, semana = week",
    },
    {
      lessonId: daymonth.id,
      prompt: 'How do you say "yesterday" in Spanish?',
      options: ["Mañana", "Hoy", "Ayer", "Ahora"],
      correctIndex: 2,
      hint: "Ayer = yesterday",
    },
    {
      lessonId: daymonth.id,
      prompt: "Translate: mañana",
      options: ["Yesterday", "Today", "Later", "Tomorrow"],
      correctIndex: 3,
      hint: "Mañana = tomorrow or morning",
    },
    {
      lessonId: daymonth.id,
      prompt: "Translate: el miércoles",
      options: ["Monday", "Friday", "Wednesday", "Sunday"],
      correctIndex: 2,
      hint: "Middle of the week",
    },

    // Time
    {
      lessonId: time.id,
      prompt: "¿Qué hora es?",
      options: [
        "What day is it?",
        "What time is it?",
        "When do we leave?",
        "How long will it take?",
      ],
      correctIndex: 1,
      hint: "Hora = hour/time",
    },
    {
      lessonId: time.id,
      prompt: "Translate: son las tres",
      options: [
        "It is one o'clock",
        "It is two o'clock",
        "It is three o'clock",
        "It is four o'clock",
      ],
      correctIndex: 2,
      hint: "Tres = three",
    },
    {
      lessonId: time.id,
      prompt: 'How do you say "half past" in Spanish?',
      options: ["En punto", "Y cuarto", "Y media", "Menos cuarto"],
      correctIndex: 2,
      hint: "Media = half",
    },
    {
      lessonId: time.id,
      prompt: "Translate: a medianoche",
      options: ["At noon", "At midnight", "In the morning", "In the evening"],
      correctIndex: 1,
      hint: "Medianoche = midnight",
    },
    {
      lessonId: time.id,
      prompt: "Translate: por la mañana",
      options: ["At night", "In the afternoon", "In the morning", "At noon"],
      correctIndex: 2,
      hint: "Mañana = morning",
    },
    {
      lessonId: time.id,
      prompt: 'How do you say "early" in Spanish?',
      options: ["Tarde", "Temprano", "Pronto", "Rápido"],
      correctIndex: 1,
      hint: "Temprano = early",
    },
    {
      lessonId: time.id,
      prompt: "Translate: son las ocho y cuarto",
      options: ["It is 8:30", "It is 7:15", "It is 8:15", "It is 9:00"],
      correctIndex: 2,
      hint: "Cuarto = quarter",
    },
    {
      lessonId: time.id,
      prompt: "Translate: tarde",
      options: ["Early", "Never", "Soon", "Late"],
      correctIndex: 3,
      hint: "Tarde = late or afternoon",
    },

    // Shopping
    {
      lessonId: shopping.id,
      prompt: "¿Cuánto cuesta esto?",
      options: [
        "Where can I buy this?",
        "What size is this?",
        "How much does this cost?",
        "Can I return this?",
      ],
      correctIndex: 2,
      hint: "Cuánto = how much, cuesta = costs",
    },
    {
      lessonId: shopping.id,
      prompt: "Translate: el precio",
      options: ["The receipt", "The discount", "The price", "The sale"],
      correctIndex: 2,
      hint: "Precio = price",
    },
    {
      lessonId: shopping.id,
      prompt: 'How do you say "expensive" in Spanish?',
      options: ["Barato", "Caro", "Gratis", "Económico"],
      correctIndex: 1,
      hint: "Caro = expensive",
    },
    {
      lessonId: shopping.id,
      prompt: "Translate: el descuento",
      options: ["The receipt", "The tax", "The total", "The discount"],
      correctIndex: 3,
      hint: "Descuento = discount",
    },
    {
      lessonId: shopping.id,
      prompt: "¿Tiene una talla más grande?",
      options: [
        "Do you have a smaller size?",
        "Do you have a different color?",
        "Do you have a larger size?",
        "Do you have this on sale?",
      ],
      correctIndex: 2,
      hint: "Grande = big/large",
    },
    {
      lessonId: shopping.id,
      prompt: "Translate: el mercado",
      options: ["The mall", "The market", "The store", "The shop"],
      correctIndex: 1,
      hint: "Mercado = market",
    },
    {
      lessonId: shopping.id,
      prompt: 'How do you say "I am just looking" in Spanish?',
      options: [
        "Quiero comprar esto",
        "Solo estoy mirando",
        "Necesito ayuda",
        "Voy a pensar",
      ],
      correctIndex: 1,
      hint: "Mirando = looking",
    },
    {
      lessonId: shopping.id,
      prompt: "Translate: la tarjeta de crédito",
      options: ["The cash", "The receipt", "The credit card", "The bank"],
      correctIndex: 2,
      hint: "Sounds very similar to English",
    },

    // Body Parts
    {
      lessonId: body.id,
      prompt: "Translate: la cabeza",
      options: ["The arm", "The leg", "The head", "The chest"],
      correctIndex: 2,
      hint: "Cabeza = head",
    },
    {
      lessonId: body.id,
      prompt: "Translate: el brazo",
      options: ["The leg", "The arm", "The hand", "The foot"],
      correctIndex: 1,
      hint: "Brazo = arm",
    },
    {
      lessonId: body.id,
      prompt: 'How do you say "knee" in Spanish?',
      options: ["Codo", "Hombro", "Rodilla", "Tobillo"],
      correctIndex: 2,
      hint: "Rodilla = knee",
    },
    {
      lessonId: body.id,
      prompt: "Translate: el estómago",
      options: ["The heart", "The stomach", "The back", "The chest"],
      correctIndex: 1,
      hint: "Sounds similar to English",
    },
    {
      lessonId: body.id,
      prompt: "Translate: los ojos",
      options: ["The ears", "The nose", "The eyes", "The mouth"],
      correctIndex: 2,
      hint: "Ojos = eyes",
    },
    {
      lessonId: body.id,
      prompt: 'How do you say "throat" in Spanish?',
      options: ["Nariz", "Garganta", "Lengua", "Mejilla"],
      correctIndex: 1,
      hint: "Garganta = throat",
    },
    {
      lessonId: body.id,
      prompt: "Translate: la espalda",
      options: ["The chest", "The shoulder", "The neck", "The back"],
      correctIndex: 3,
      hint: "Espalda = back",
    },
    {
      lessonId: body.id,
      prompt: "Translate: el pie",
      options: ["The leg", "The toe", "The foot", "The ankle"],
      correctIndex: 2,
      hint: "Pie = foot",
    },

    // Doctor
    {
      lessonId: doctor.id,
      prompt: "Translate: me duele la cabeza",
      options: [
        "I have a stomachache",
        "I have a headache",
        "I have a sore throat",
        "I have a fever",
      ],
      correctIndex: 1,
      hint: "Cabeza = head, duele = hurts",
    },
    {
      lessonId: doctor.id,
      prompt: "Translate: la fiebre",
      options: ["The cold", "The cough", "The fever", "The allergy"],
      correctIndex: 2,
      hint: "Fiebre = fever",
    },
    {
      lessonId: doctor.id,
      prompt: 'How do you say "I need a doctor" in Spanish?',
      options: [
        "Llame a la policía",
        "Necesito un médico",
        "Quiero una enfermera",
        "Tengo una cita",
      ],
      correctIndex: 1,
      hint: "Médico = doctor",
    },
    {
      lessonId: doctor.id,
      prompt: "Translate: la medicina",
      options: ["The hospital", "The pharmacy", "The medicine", "The surgery"],
      correctIndex: 2,
      hint: "Sounds like medicine",
    },
    {
      lessonId: doctor.id,
      prompt: "Translate: estoy mareado",
      options: ["I am tired", "I am in pain", "I am dizzy", "I am sick"],
      correctIndex: 2,
      hint: "Mareado = dizzy",
    },
    {
      lessonId: doctor.id,
      prompt: 'How do you say "pharmacy" in Spanish?',
      options: ["Hospital", "Clínica", "Farmacia", "Consultorio"],
      correctIndex: 2,
      hint: "Farmacia = pharmacy",
    },
    {
      lessonId: doctor.id,
      prompt: "Translate: la receta",
      options: [
        "The appointment",
        "The prescription",
        "The diagnosis",
        "The treatment",
      ],
      correctIndex: 1,
      hint: "Receta = prescription or recipe",
    },
    {
      lessonId: doctor.id,
      prompt: "Translate: me siento mal",
      options: ["I feel great", "I feel tired", "I feel sick", "I feel better"],
      correctIndex: 2,
      hint: "Mal = bad",
    },

    // Emotions
    {
      lessonId: emotions.id,
      prompt: "Translate: estoy feliz",
      options: ["I am sad", "I am tired", "I am happy", "I am angry"],
      correctIndex: 2,
      hint: "Feliz = happy",
    },
    {
      lessonId: emotions.id,
      prompt: "Translate: estoy triste",
      options: ["I am happy", "I am sad", "I am bored", "I am scared"],
      correctIndex: 1,
      hint: "Triste = sad",
    },
    {
      lessonId: emotions.id,
      prompt: 'How do you say "I am angry" in Spanish?',
      options: [
        "Estoy nervioso",
        "Estoy aburrido",
        "Estoy enojado",
        "Estoy asustado",
      ],
      correctIndex: 2,
      hint: "Enojado = angry",
    },
    {
      lessonId: emotions.id,
      prompt: "Translate: estoy cansado",
      options: ["I am hungry", "I am bored", "I am tired", "I am sick"],
      correctIndex: 2,
      hint: "Cansado = tired",
    },
    {
      lessonId: emotions.id,
      prompt: "Translate: estoy emocionado",
      options: [
        "I am worried",
        "I am excited",
        "I am surprised",
        "I am nervous",
      ],
      correctIndex: 1,
      hint: "Emocionado = excited",
    },
    {
      lessonId: emotions.id,
      prompt: 'How do you say "I am scared" in Spanish?',
      options: [
        "Estoy triste",
        "Estoy enojado",
        "Estoy aburrido",
        "Estoy asustado",
      ],
      correctIndex: 3,
      hint: "Asustado = scared",
    },
    {
      lessonId: emotions.id,
      prompt: "Translate: estoy nervioso",
      options: [
        "I am excited",
        "I am nervous",
        "I am worried",
        "I am confused",
      ],
      correctIndex: 1,
      hint: "Nervioso = nervous",
    },
    {
      lessonId: emotions.id,
      prompt: "Translate: me siento bien",
      options: ["I feel sick", "I feel tired", "I feel well", "I feel sad"],
      correctIndex: 2,
      hint: "Bien = well/good",
    },

    // Animals
    {
      lessonId: animals.id,
      prompt: "Translate: el perro",
      options: ["The cat", "The bird", "The dog", "The fish"],
      correctIndex: 2,
      hint: "Perro = dog",
    },
    {
      lessonId: animals.id,
      prompt: "Translate: el gato",
      options: ["The dog", "The cat", "The rabbit", "The mouse"],
      correctIndex: 1,
      hint: "Gato = cat",
    },
    {
      lessonId: animals.id,
      prompt: 'How do you say "horse" in Spanish?',
      options: ["Vaca", "Cerdo", "Caballo", "Oveja"],
      correctIndex: 2,
      hint: "Caballo = horse",
    },
    {
      lessonId: animals.id,
      prompt: "Translate: el pájaro",
      options: ["The fish", "The snake", "The insect", "The bird"],
      correctIndex: 3,
      hint: "Pájaro = bird",
    },
    {
      lessonId: animals.id,
      prompt: "Translate: el león",
      options: ["The tiger", "The bear", "The wolf", "The lion"],
      correctIndex: 3,
      hint: "León sounds like lion",
    },
    {
      lessonId: animals.id,
      prompt: 'How do you say "fish" in Spanish?',
      options: ["Pez", "Rana", "Tortuga", "Serpiente"],
      correctIndex: 0,
      hint: "Pez = fish",
    },
    {
      lessonId: animals.id,
      prompt: "Translate: la mariposa",
      options: ["The bee", "The ant", "The butterfly", "The spider"],
      correctIndex: 2,
      hint: "Mariposa = butterfly",
    },
    {
      lessonId: animals.id,
      prompt: "Translate: el elefante",
      options: ["The giraffe", "The elephant", "The rhino", "The hippo"],
      correctIndex: 1,
      hint: "Sounds just like elephant",
    },

    // Nature
    {
      lessonId: nature.id,
      prompt: "Translate: el árbol",
      options: ["The flower", "The grass", "The tree", "The bush"],
      correctIndex: 2,
      hint: "Árbol = tree",
    },
    {
      lessonId: nature.id,
      prompt: "Translate: el río",
      options: ["The lake", "The ocean", "The river", "The stream"],
      correctIndex: 2,
      hint: "Río = river",
    },
    {
      lessonId: nature.id,
      prompt: 'How do you say "mountain" in Spanish?',
      options: ["Valle", "Colina", "Montaña", "Volcán"],
      correctIndex: 2,
      hint: "Montaña = mountain",
    },
    {
      lessonId: nature.id,
      prompt: "Translate: la playa",
      options: ["The forest", "The beach", "The desert", "The island"],
      correctIndex: 1,
      hint: "Playa = beach",
    },
    {
      lessonId: nature.id,
      prompt: "Translate: el bosque",
      options: ["The jungle", "The meadow", "The forest", "The swamp"],
      correctIndex: 2,
      hint: "Bosque = forest",
    },
    {
      lessonId: nature.id,
      prompt: 'How do you say "sun" in Spanish?',
      options: ["Luna", "Estrella", "Nube", "Sol"],
      correctIndex: 3,
      hint: "Sol = sun",
    },
    {
      lessonId: nature.id,
      prompt: "Translate: la luna",
      options: ["The sun", "The moon", "The star", "The sky"],
      correctIndex: 1,
      hint: "Luna = moon",
    },
    {
      lessonId: nature.id,
      prompt: "Translate: el mar",
      options: ["The lake", "The river", "The sea", "The bay"],
      correctIndex: 2,
      hint: "Mar = sea",
    },

    // Sports
    {
      lessonId: sports.id,
      prompt: "Translate: el fútbol",
      options: ["Basketball", "Baseball", "Soccer", "Tennis"],
      correctIndex: 2,
      hint: "Fútbol = soccer/football",
    },
    {
      lessonId: sports.id,
      prompt: "Translate: nadar",
      options: ["To run", "To jump", "To swim", "To cycle"],
      correctIndex: 2,
      hint: "Nadar = to swim",
    },
    {
      lessonId: sports.id,
      prompt: 'How do you say "team" in Spanish?',
      options: ["Jugador", "Equipo", "Partido", "Liga"],
      correctIndex: 1,
      hint: "Equipo = team",
    },
    {
      lessonId: sports.id,
      prompt: "Translate: el campeón",
      options: ["The player", "The coach", "The referee", "The champion"],
      correctIndex: 3,
      hint: "Campeón = champion",
    },
    {
      lessonId: sports.id,
      prompt: "Translate: correr",
      options: ["To walk", "To jump", "To run", "To climb"],
      correctIndex: 2,
      hint: "Correr = to run",
    },
    {
      lessonId: sports.id,
      prompt: 'How do you say "match" or "game" in Spanish?',
      options: ["Equipo", "Estadio", "Partido", "Torneo"],
      correctIndex: 2,
      hint: "Partido = match/game",
    },
    {
      lessonId: sports.id,
      prompt: "Translate: ganar",
      options: ["To lose", "To tie", "To play", "To win"],
      correctIndex: 3,
      hint: "Ganar = to win",
    },
    {
      lessonId: sports.id,
      prompt: "Translate: el entrenador",
      options: ["The player", "The coach", "The fan", "The referee"],
      correctIndex: 1,
      hint: "Entrenador = coach/trainer",
    },

    // Hobbies
    {
      lessonId: hobbies.id,
      prompt: "Translate: me gusta leer",
      options: [
        "I like to write",
        "I like to sing",
        "I like to read",
        "I like to draw",
      ],
      correctIndex: 2,
      hint: "Leer = to read",
    },
    {
      lessonId: hobbies.id,
      prompt: "Translate: pintar",
      options: ["To sculpt", "To draw", "To paint", "To craft"],
      correctIndex: 2,
      hint: "Pintar = to paint",
    },
    {
      lessonId: hobbies.id,
      prompt: 'How do you say "cooking" in Spanish?',
      options: ["Bailar", "Cocinar", "Cantar", "Tejer"],
      correctIndex: 1,
      hint: "Cocinar = to cook",
    },
    {
      lessonId: hobbies.id,
      prompt: "Translate: viajar",
      options: ["To hike", "To camp", "To travel", "To explore"],
      correctIndex: 2,
      hint: "Viajar = to travel",
    },
    {
      lessonId: hobbies.id,
      prompt: "Translate: tocar la guitarra",
      options: [
        "To listen to guitar",
        "To buy a guitar",
        "To play guitar",
        "To teach guitar",
      ],
      correctIndex: 2,
      hint: "Tocar = to play (instrument)",
    },
    {
      lessonId: hobbies.id,
      prompt: 'How do you say "photography" in Spanish?',
      options: ["Dibujo", "Fotografía", "Escultura", "Cerámica"],
      correctIndex: 1,
      hint: "Sounds similar to photography",
    },
    {
      lessonId: hobbies.id,
      prompt: "Translate: bailar",
      options: ["To sing", "To act", "To dance", "To perform"],
      correctIndex: 2,
      hint: "Bailar = to dance",
    },
    {
      lessonId: hobbies.id,
      prompt: "Translate: ¿cuál es tu pasatiempo?",
      options: [
        "What is your job?",
        "What is your hobby?",
        "What is your goal?",
        "What is your talent?",
      ],
      correctIndex: 1,
      hint: "Pasatiempo = hobby",
    },

    // Work
    {
      lessonId: work.id,
      prompt: "Translate: el trabajo",
      options: ["The vacation", "The salary", "The work", "The office"],
      correctIndex: 2,
      hint: "Trabajo = work/job",
    },
    {
      lessonId: work.id,
      prompt: "Translate: el jefe",
      options: ["The employee", "The client", "The colleague", "The boss"],
      correctIndex: 3,
      hint: "Jefe = boss/chief",
    },
    {
      lessonId: work.id,
      prompt: 'How do you say "meeting" in Spanish?',
      options: ["Conferencia", "Reunión", "Presentación", "Entrevista"],
      correctIndex: 1,
      hint: "Reunión = meeting",
    },
    {
      lessonId: work.id,
      prompt: "Translate: el sueldo",
      options: ["The bonus", "The tax", "The salary", "The budget"],
      correctIndex: 2,
      hint: "Sueldo = salary",
    },
    {
      lessonId: work.id,
      prompt: "Translate: trabajar desde casa",
      options: [
        "To work overtime",
        "To work from home",
        "To work part-time",
        "To work abroad",
      ],
      correctIndex: 1,
      hint: "Casa = home",
    },
    {
      lessonId: work.id,
      prompt: 'How do you say "interview" in Spanish?',
      options: ["Solicitud", "Currículum", "Entrevista", "Contrato"],
      correctIndex: 2,
      hint: "Entrevista = interview",
    },
    {
      lessonId: work.id,
      prompt: "Translate: el colega",
      options: ["The client", "The boss", "The colleague", "The intern"],
      correctIndex: 2,
      hint: "Sounds like colleague",
    },
    {
      lessonId: work.id,
      prompt: "Translate: estoy de vacaciones",
      options: [
        "I am at work",
        "I am at a meeting",
        "I am on vacation",
        "I am working late",
      ],
      correctIndex: 2,
      hint: "Vacaciones = vacation",
    },

    // School
    {
      lessonId: school.id,
      prompt: "Translate: el estudiante",
      options: ["The teacher", "The principal", "The student", "The librarian"],
      correctIndex: 2,
      hint: "Estudiante = student",
    },
    {
      lessonId: school.id,
      prompt: "Translate: la tarea",
      options: ["The test", "The homework", "The class", "The project"],
      correctIndex: 1,
      hint: "Tarea = homework",
    },
    {
      lessonId: school.id,
      prompt: 'How do you say "library" in Spanish?',
      options: ["Librería", "Biblioteca", "Laboratorio", "Auditorio"],
      correctIndex: 1,
      hint: "Biblioteca = library (not librería!)",
    },
    {
      lessonId: school.id,
      prompt: "Translate: el examen",
      options: ["The grade", "The class", "The exam", "The lesson"],
      correctIndex: 2,
      hint: "Examen = exam",
    },
    {
      lessonId: school.id,
      prompt: "Translate: aprender",
      options: ["To teach", "To study", "To learn", "To read"],
      correctIndex: 2,
      hint: "Aprender = to learn",
    },
    {
      lessonId: school.id,
      prompt: 'How do you say "backpack" in Spanish?',
      options: ["Bolso", "Maletín", "Mochila", "Cartera"],
      correctIndex: 2,
      hint: "Mochila = backpack",
    },
    {
      lessonId: school.id,
      prompt: "Translate: el recreo",
      options: ["The classroom", "The recess", "The cafeteria", "The hallway"],
      correctIndex: 1,
      hint: "Recreo = recess/break",
    },
    {
      lessonId: school.id,
      prompt: "Translate: sacar buenas notas",
      options: [
        "To fail a class",
        "To skip school",
        "To get good grades",
        "To take notes",
      ],
      correctIndex: 2,
      hint: "Notas = grades",
    },

    // Technology
    {
      lessonId: tech.id,
      prompt: "Translate: el teléfono",
      options: ["The computer", "The tablet", "The phone", "The camera"],
      correctIndex: 2,
      hint: "Teléfono = telephone/phone",
    },
    {
      lessonId: tech.id,
      prompt: "Translate: la computadora",
      options: ["The phone", "The computer", "The printer", "The keyboard"],
      correctIndex: 1,
      hint: "Computadora = computer",
    },
    {
      lessonId: tech.id,
      prompt: 'How do you say "internet" in Spanish?',
      options: ["La red", "El internet", "La web", "El sistema"],
      correctIndex: 1,
      hint: "Same word!",
    },
    {
      lessonId: tech.id,
      prompt: "Translate: enviar un mensaje",
      options: [
        "To receive a message",
        "To delete a message",
        "To send a message",
        "To read a message",
      ],
      correctIndex: 2,
      hint: "Enviar = to send",
    },
    {
      lessonId: tech.id,
      prompt: "Translate: la contraseña",
      options: ["The username", "The email", "The account", "The password"],
      correctIndex: 3,
      hint: "Contraseña = password",
    },
    {
      lessonId: tech.id,
      prompt: 'How do you say "to charge (a phone)" in Spanish?',
      options: ["Encender", "Apagar", "Cargar", "Conectar"],
      correctIndex: 2,
      hint: "Cargar = to charge/load",
    },
    {
      lessonId: tech.id,
      prompt: "Translate: las redes sociales",
      options: ["The news", "The apps", "The social media", "The internet"],
      correctIndex: 2,
      hint: "Redes = networks, sociales = social",
    },
    {
      lessonId: tech.id,
      prompt: "Translate: descargar",
      options: ["To upload", "To stream", "To download", "To share"],
      correctIndex: 2,
      hint: "Descargar = to download",
    },

    // Directions
    {
      lessonId: directions.id,
      prompt: "Translate: a la derecha",
      options: ["Straight ahead", "To the left", "To the right", "Behind you"],
      correctIndex: 2,
      hint: "Derecha = right",
    },
    {
      lessonId: directions.id,
      prompt: "Translate: a la izquierda",
      options: ["To the right", "To the left", "Straight ahead", "Behind"],
      correctIndex: 1,
      hint: "Izquierda = left",
    },
    {
      lessonId: directions.id,
      prompt: 'How do you say "straight ahead" in Spanish?',
      options: ["A la derecha", "Atrás", "Todo recto", "A la izquierda"],
      correctIndex: 2,
      hint: "Recto = straight",
    },
    {
      lessonId: directions.id,
      prompt: "Translate: la calle",
      options: ["The avenue", "The highway", "The street", "The alley"],
      correctIndex: 2,
      hint: "Calle = street",
    },
    {
      lessonId: directions.id,
      prompt: "Translate: doblar a la derecha",
      options: ["Go straight", "Turn left", "Turn right", "Turn around"],
      correctIndex: 2,
      hint: "Doblar = to turn",
    },
    {
      lessonId: directions.id,
      prompt: 'How do you say "near" in Spanish?',
      options: ["Lejos", "Aquí", "Cerca", "Allí"],
      correctIndex: 2,
      hint: "Cerca = near/close",
    },
    {
      lessonId: directions.id,
      prompt: "Translate: ¿dónde está el banco?",
      options: [
        "Where is the store?",
        "Where is the bank?",
        "Where is the park?",
        "Where is the hospital?",
      ],
      correctIndex: 1,
      hint: "Banco = bank",
    },
    {
      lessonId: directions.id,
      prompt: "Translate: cruzar la calle",
      options: [
        "To walk down the street",
        "To cross the street",
        "To follow the street",
        "To turn at the street",
      ],
      correctIndex: 1,
      hint: "Cruzar = to cross",
    },

    // Transport
    {
      lessonId: transport.id,
      prompt: "Translate: el autobús",
      options: ["The train", "The subway", "The bus", "The tram"],
      correctIndex: 2,
      hint: "Autobús = bus",
    },
    {
      lessonId: transport.id,
      prompt: "Translate: el metro",
      options: ["The bus", "The taxi", "The subway", "The tram"],
      correctIndex: 2,
      hint: "Metro = subway/metro",
    },
    {
      lessonId: transport.id,
      prompt: 'How do you say "ticket" in Spanish?',
      options: ["Asiento", "Andén", "Billete", "Horario"],
      correctIndex: 2,
      hint: "Billete = ticket (transport)",
    },
    {
      lessonId: transport.id,
      prompt: "Translate: el horario",
      options: ["The route", "The stop", "The platform", "The schedule"],
      correctIndex: 3,
      hint: "Horario = schedule/timetable",
    },
    {
      lessonId: transport.id,
      prompt: "Translate: perder el tren",
      options: [
        "To catch the train",
        "To miss the train",
        "To take the train",
        "To board the train",
      ],
      correctIndex: 1,
      hint: "Perder = to miss/lose",
    },
    {
      lessonId: transport.id,
      prompt: 'How do you say "platform" in Spanish?',
      options: ["Estación", "Andén", "Taquilla", "Pasillo"],
      correctIndex: 1,
      hint: "Andén = platform",
    },
    {
      lessonId: transport.id,
      prompt: "Translate: el vuelo",
      options: ["The train", "The cruise", "The flight", "The bus"],
      correctIndex: 2,
      hint: "Vuelo = flight",
    },
    {
      lessonId: transport.id,
      prompt: "Translate: hacer transbordo",
      options: [
        "To buy a ticket",
        "To check luggage",
        "To transfer",
        "To board",
      ],
      correctIndex: 2,
      hint: "Transbordo = transfer/connection",
    },

    // Clothes
    {
      lessonId: clothes.id,
      prompt: "Translate: la camisa",
      options: ["The jacket", "The shirt", "The pants", "The dress"],
      correctIndex: 1,
      hint: "Camisa = shirt",
    },
    {
      lessonId: clothes.id,
      prompt: "Translate: los zapatos",
      options: ["The socks", "The boots", "The shoes", "The sandals"],
      correctIndex: 2,
      hint: "Zapatos = shoes",
    },
    {
      lessonId: clothes.id,
      prompt: 'How do you say "dress" in Spanish?',
      options: ["Falda", "Blusa", "Vestido", "Abrigo"],
      correctIndex: 2,
      hint: "Vestido = dress",
    },
    {
      lessonId: clothes.id,
      prompt: "Translate: el abrigo",
      options: ["The shirt", "The coat", "The hat", "The scarf"],
      correctIndex: 1,
      hint: "Abrigo = coat/overcoat",
    },
    {
      lessonId: clothes.id,
      prompt: "Translate: llevar puesto",
      options: ["To buy clothes", "To try on", "To wear", "To wash"],
      correctIndex: 2,
      hint: "Llevar puesto = to wear/have on",
    },
    {
      lessonId: clothes.id,
      prompt: 'How do you say "size" in Spanish?',
      options: ["Color", "Precio", "Talla", "Marca"],
      correctIndex: 2,
      hint: "Talla = size (clothing)",
    },
    {
      lessonId: clothes.id,
      prompt: "Translate: los pantalones",
      options: ["The shorts", "The jeans", "The pants", "The leggings"],
      correctIndex: 2,
      hint: "Pantalones = pants/trousers",
    },
    {
      lessonId: clothes.id,
      prompt: "Translate: ¿me queda bien?",
      options: [
        "Is it expensive?",
        "Does it fit me?",
        "Is it in stock?",
        "Can I return it?",
      ],
      correctIndex: 1,
      hint: "Quedar = to fit/suit",
    },

    // House & Home
    {
      lessonId: house.id,
      prompt: "Translate: la cocina",
      options: [
        "The bedroom",
        "The bathroom",
        "The kitchen",
        "The living room",
      ],
      correctIndex: 2,
      hint: "Cocina = kitchen",
    },
    {
      lessonId: house.id,
      prompt: "Translate: el dormitorio",
      options: ["The bathroom", "The bedroom", "The hallway", "The garage"],
      correctIndex: 1,
      hint: "Dormir = to sleep, dormitorio = bedroom",
    },
    {
      lessonId: house.id,
      prompt: 'How do you say "living room" in Spanish?',
      options: ["El comedor", "El pasillo", "La terraza", "La sala"],
      correctIndex: 3,
      hint: "Sala = living room",
    },
    {
      lessonId: house.id,
      prompt: "Translate: limpiar la casa",
      options: [
        "To build the house",
        "To buy the house",
        "To clean the house",
        "To sell the house",
      ],
      correctIndex: 2,
      hint: "Limpiar = to clean",
    },
    {
      lessonId: house.id,
      prompt: "Translate: el alquiler",
      options: ["The mortgage", "The rent", "The deposit", "The bill"],
      correctIndex: 1,
      hint: "Alquiler = rent",
    },
    {
      lessonId: house.id,
      prompt: 'How do you say "neighbor" in Spanish?',
      options: ["Compañero", "Vecino", "Inquilino", "Propietario"],
      correctIndex: 1,
      hint: "Vecino = neighbor",
    },
    {
      lessonId: house.id,
      prompt: "Translate: las llaves",
      options: ["The windows", "The doors", "The keys", "The locks"],
      correctIndex: 2,
      hint: "Llaves = keys",
    },
    {
      lessonId: house.id,
      prompt: "Translate: mudarse",
      options: ["To clean up", "To renovate", "To move house", "To rent out"],
      correctIndex: 2,
      hint: "Mudarse = to move (house)",
    },

    // Celebrations
    {
      lessonId: celebrations.id,
      prompt: "Translate: ¡feliz cumpleaños!",
      options: [
        "Happy New Year!",
        "Congratulations!",
        "Happy Birthday!",
        "Happy Anniversary!",
      ],
      correctIndex: 2,
      hint: "Cumpleaños = birthday",
    },
    {
      lessonId: celebrations.id,
      prompt: "Translate: la fiesta",
      options: ["The dinner", "The party", "The ceremony", "The parade"],
      correctIndex: 1,
      hint: "Fiesta = party/festival",
    },
    {
      lessonId: celebrations.id,
      prompt: 'How do you say "Happy New Year" in Spanish?',
      options: [
        "Feliz Navidad",
        "Feliz Año Nuevo",
        "Buena suerte",
        "Felicidades",
      ],
      correctIndex: 1,
      hint: "Año = year, nuevo = new",
    },
    {
      lessonId: celebrations.id,
      prompt: "Translate: el regalo",
      options: ["The cake", "The card", "The gift", "The balloon"],
      correctIndex: 2,
      hint: "Regalo = gift/present",
    },
    {
      lessonId: celebrations.id,
      prompt: "Translate: brindar",
      options: ["To celebrate", "To invite", "To toast", "To decorate"],
      correctIndex: 2,
      hint: "Brindar = to toast (with drinks)",
    },
    {
      lessonId: celebrations.id,
      prompt: 'How do you say "Merry Christmas" in Spanish?',
      options: [
        "Feliz Año Nuevo",
        "Felices Fiestas",
        "Feliz Navidad",
        "Buenas fiestas",
      ],
      correctIndex: 2,
      hint: "Navidad = Christmas",
    },
    {
      lessonId: celebrations.id,
      prompt: "Translate: la vela",
      options: ["The balloon", "The candle", "The decoration", "The confetti"],
      correctIndex: 1,
      hint: "Vela = candle",
    },
    {
      lessonId: celebrations.id,
      prompt: "Translate: ¡salud!",
      options: ["Goodbye!", "Good luck!", "Thank you!", "Cheers!"],
      correctIndex: 3,
      hint: "Salud = health/cheers",
    },

    // Music
    {
      lessonId: music.id,
      prompt: "Translate: la música",
      options: ["The dance", "The song", "The music", "The concert"],
      correctIndex: 2,
      hint: "Música = music",
    },
    {
      lessonId: music.id,
      prompt: "Translate: la canción",
      options: ["The concert", "The singer", "The lyrics", "The song"],
      correctIndex: 3,
      hint: "Canción = song",
    },
    {
      lessonId: music.id,
      prompt: 'How do you say "guitar" in Spanish?',
      options: ["Violín", "Guitarra", "Batería", "Piano"],
      correctIndex: 1,
      hint: "Guitarra = guitar",
    },
    {
      lessonId: music.id,
      prompt: "Translate: escuchar música",
      options: [
        "To play music",
        "To write music",
        "To listen to music",
        "To record music",
      ],
      correctIndex: 2,
      hint: "Escuchar = to listen",
    },
    {
      lessonId: music.id,
      prompt: "Translate: el cantante",
      options: ["The musician", "The dancer", "The singer", "The composer"],
      correctIndex: 2,
      hint: "Cantar = to sing, cantante = singer",
    },
    {
      lessonId: music.id,
      prompt: 'How do you say "concert" in Spanish?',
      options: ["Espectáculo", "Concierto", "Festival", "Actuación"],
      correctIndex: 1,
      hint: "Concierto = concert",
    },
    {
      lessonId: music.id,
      prompt: "Translate: la letra",
      options: ["The melody", "The rhythm", "The lyrics", "The chorus"],
      correctIndex: 2,
      hint: "Letra = letter/lyrics",
    },
    {
      lessonId: music.id,
      prompt: "Translate: ¿qué tipo de música te gusta?",
      options: [
        "Who is your favorite singer?",
        "What type of music do you like?",
        "Do you play an instrument?",
        "Have you been to a concert?",
      ],
      correctIndex: 1,
      hint: "Tipo = type, gusta = like",
    },

    // Movies & TV
    {
      lessonId: movies.id,
      prompt: "Translate: la película",
      options: ["The series", "The movie", "The episode", "The channel"],
      correctIndex: 1,
      hint: "Película = movie/film",
    },
    {
      lessonId: movies.id,
      prompt: "Translate: el actor",
      options: ["The director", "The producer", "The actor", "The writer"],
      correctIndex: 2,
      hint: "Same word!",
    },
    {
      lessonId: movies.id,
      prompt: 'How do you say "subtitles" in Spanish?',
      options: ["Doblaje", "Subtítulos", "Traducción", "Diálogo"],
      correctIndex: 1,
      hint: "Subtítulos = subtitles",
    },
    {
      lessonId: movies.id,
      prompt: "Translate: el estreno",
      options: ["The trailer", "The sequel", "The premiere", "The review"],
      correctIndex: 2,
      hint: "Estreno = premiere/release",
    },
    {
      lessonId: movies.id,
      prompt: "Translate: me encantó la película",
      options: [
        "I hated the movie",
        "I liked the movie",
        "I loved the movie",
        "I watched the movie",
      ],
      correctIndex: 2,
      hint: "Encantar = to love (something)",
    },
    {
      lessonId: movies.id,
      prompt: 'How do you say "remote control" in Spanish?',
      options: ["Televisor", "Mando a distancia", "Control remoto", "Pantalla"],
      correctIndex: 2,
      hint: "Control remoto = remote control",
    },
    {
      lessonId: movies.id,
      prompt: "Translate: el género",
      options: ["The rating", "The genre", "The cast", "The plot"],
      correctIndex: 1,
      hint: "Género = genre",
    },
    {
      lessonId: movies.id,
      prompt: "Translate: ¿qué dan en la tele esta noche?",
      options: [
        "What time does it start?",
        "What is on TV tonight?",
        "Where can I watch it?",
        "Who is the director?",
      ],
      correctIndex: 1,
      hint: "Dan = show/broadcast, tele = TV",
    },

    // Advanced
    {
      lessonId: advanced.id,
      prompt: "Translate: a pesar de",
      options: ["Because of", "In spite of", "Instead of", "According to"],
      correctIndex: 1,
      hint: "A pesar de = in spite of/despite",
    },
    {
      lessonId: advanced.id,
      prompt: "Translate: sin embargo",
      options: ["Therefore", "In addition", "However", "On the other hand"],
      correctIndex: 2,
      hint: "Sin embargo = however/nevertheless",
    },
    {
      lessonId: advanced.id,
      prompt: 'How do you say "as soon as possible" in Spanish?',
      options: [
        "Tarde o temprano",
        "Lo antes posible",
        "De vez en cuando",
        "A tiempo",
      ],
      correctIndex: 1,
      hint: "Lo antes posible = ASAP",
    },
    {
      lessonId: advanced.id,
      prompt: "Translate: llevar a cabo",
      options: ["To give up", "To take apart", "To carry out", "To hold back"],
      correctIndex: 2,
      hint: "Llevar a cabo = to carry out/accomplish",
    },
    {
      lessonId: advanced.id,
      prompt: "Translate: de hecho",
      options: ["In fact", "After all", "As a result", "On the contrary"],
      correctIndex: 0,
      hint: "De hecho = in fact/actually",
    },
    {
      lessonId: advanced.id,
      prompt: 'How do you say "on the other hand" in Spanish?',
      options: ["Por lo tanto", "Por otro lado", "Sin embargo", "A causa de"],
      correctIndex: 1,
      hint: "Otro = other, lado = side",
    },
    {
      lessonId: advanced.id,
      prompt: "Translate: a menos que",
      options: ["As long as", "Even though", "Unless", "So that"],
      correctIndex: 2,
      hint: "A menos que = unless",
    },
    {
      lessonId: advanced.id,
      prompt: "Translate: por lo tanto",
      options: ["However", "Although", "Therefore", "Meanwhile"],
      correctIndex: 2,
      hint: "Por lo tanto = therefore/thus",
    },
  ]);

  console.log("Done! 25 lessons seeded.");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
